// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcT0jmdoGbqcFXG3RnegxOsuayRVggMG8',
    appId: '1:242525443214:web:bd7b953c56f850836fa5df',
    messagingSenderId: '242525443214',
    projectId: 'chatapp-3bbd5',
    authDomain: 'chatapp-3bbd5.firebaseapp.com',
    storageBucket: 'chatapp-3bbd5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbuNO6A843mFb6vWUXavtFuKbN9t0dEzc',
    appId: '1:242525443214:android:5464f72f9b2bcf7f6fa5df',
    messagingSenderId: '242525443214',
    projectId: 'chatapp-3bbd5',
    storageBucket: 'chatapp-3bbd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-Damn0vTV8jnM0fmlCKNRTYaX0e9Uljo',
    appId: '1:242525443214:ios:bf285a91365507456fa5df',
    messagingSenderId: '242525443214',
    projectId: 'chatapp-3bbd5',
    storageBucket: 'chatapp-3bbd5.appspot.com',
    iosClientId: '242525443214-hs00aaesc7ls8588oe6l19uc7btceku8.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatMessengerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-Damn0vTV8jnM0fmlCKNRTYaX0e9Uljo',
    appId: '1:242525443214:ios:c0114dd5e6399bcc6fa5df',
    messagingSenderId: '242525443214',
    projectId: 'chatapp-3bbd5',
    storageBucket: 'chatapp-3bbd5.appspot.com',
    iosClientId: '242525443214-4aoe13f73ueb15boihq6i4aq89hallvo.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatMessengerapp.RunnerTests',
  );
}
